### PR TITLE
upickle addon

### PR DESCRIPTION
**Pull request by vic**
Allows message serialization via [upickle](http://www.lihaoyi.com/upickle)

### CODE REVIEW

**Comment by vic** [comment]
Travis jdk setup is failing with `Expected feature release number in range of 9 to 14, but got: 7`

**Comment by timcharper** [comment]
I've updated the Travis config here: https://github.com/SpinGo/op-rabbit/pull/179

**Comment by timcharper** [comment]
@vic can you rebase this with the travis CI fixes?

**Comment by vic** [comment]
@timcharper this branch is ready

**Comment by timcharper** [comment]
Merged. Thank you!

**Pull request merged**
