### PR TITLE
Update README.md (Queue.passive)

### PR DESCRIPTION
**Pull request by unthingable**
#45

### CODE REVIEW

**Comment by timcharper** [comment]
The failures aren't being logged? I find that to be intolerable and would prefer to fix them, than to advertise them.

A future is returned by the subscription method, the failure to bind is definitely propagated through that.

Thanks for the report. I'm going to see about logging the error quickly.

**Comment by timcharper** [comment]
The silent failure is resolved by 9984d722e81c0858c227acc9eb1cc0a207ad9756; can you update your pull request?

**Comment by unthingable** [comment]
Thanks! Pull request updated.

**Comment by timcharper** [comment]
Travis CI is a new thing and looks like there might be a brittle test.

**Pull request merged**
