### PR TITLE
Travis doesn't support jdk-7 anymore

### PR DESCRIPTION
**Pull request by timcharper**

### CODE REVIEW

**Comment by vic** [comment]
I'd recommend also adding a LTS release like jdk 11.

**Comment by vic** [comment]
@timcharper Looks like rabbitmq is not starting during CI: https://travis-ci.org/SpinGo/op-rabbit/jobs/593113419#L180

And according to this link:
https://travis-ci.community/t/is-rabbitmq-service-down/4362

We'd probably have to add 
```yaml
distro: trusty
```
until rabbitmq is available in xenial (now the default distro in travis).

**Comment by vic** [comment]
After trying this in a branch of mine, looks like using trusty does starts rabbitmq.

But now the tests fail with https://travis-ci.com/vic/op-rabbit/jobs/241781941#L814, I'm trying to investigate and see what's wrong, but maybe you have a better idea on what's happening.

**Comment by timcharper** [comment]
Thanks, @vic! That test is actually passing (it's testing that the recovery strategy eventually gives up, I believe?). Look at the bottom, it says sbt test exits with status `0`, but then at the very end it says status `1` 😕

**Comment by timcharper** [comment]
Super weird, at least the tests are passing now. I have no idea why it says things are failing. This will be really helpful at least to merge future PRs getting these statuses at least legible if I click through the logs

**Comment by vic** [comment]
#180 is passing now :)

**Pull request closed without merging**
